import os 

# email variables
USERNAME_GMAIL = os.environ.get('USERNAME_GMAIL')
PASSWORD_GMAIL = os.environ.get('PASSWORD_GMAIL')

#database variabes
HOST_DATABASE = os.environ.get('HOST_DATABASE') 
USERNAME_DATABASE_TRACKING = os.environ.get('USERNAME_DATABASE_TRACKING')
PASSWORD_DATABASE_TRACKING = os.environ.get('PASSWORD_DATABASE_TRACKING')
DATABASE_TRACKING  = os.environ.get('DATABASE_TRACKING')